import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./navBar/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Daily - Flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* <NavBar /> */}
      {/* <body className="min-h-full flex flex-col ">{children}</body> */}

      <body className="flex min-h-screen">
        {/* Sidebar (debug color) */}
        <div className="w-60 bg-red-300">
          <NavBar />
        </div>

        {/* Content (debug color) */}
        <main className="flex-1 bg-green-300 p-6">{children}</main>
      </body>
    </html>
  );
}
